### ISSUE TITLE
Traceback (most recent call last) Error Show me

### ISSUE THREAD

**Issue by FranklinOP-IND** [colinhartigan/valorant-skin-cli#17]
![image](https://user-images.githubusercontent.com/64591314/124434859-03951e00-dd92-11eb-98e8-2fd4242e9c47.png)

**Comment by colinhartigan** [comment]
try [v1.0](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0)

**Comment by colinhartigan** [comment]
closed for inactivity, likely a bug from using old version
