### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by iramsesvl** [colinhartigan/valorant-skin-cli#18]
when I open the run.bat file it opens and shows me a window where it says Valorant skin but then it closes and I can't use it

![image](https://user-images.githubusercontent.com/86082372/124507101-eb1d0780-dd81-11eb-878e-a3b504733600.png)
 that's the only thing I see and it closes

**Comment by colinhartigan** [comment]
try [v1.0](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0)

**Comment by colinhartigan** [comment]
closed for inactivity
