### ISSUE TITLE
don't working

### ISSUE THREAD

**Issue by Raymond-001** [colinhartigan/valorant-skin-cli#22]
I do everything but the skins do not change,maybe you should make a video showing how it works.

**Comment by HoangTheBoss** [comment]
there is a video on the main repository site

**Comment by Raymond-001** [comment]
look https://youtu.be/v5fnLZrtU7M

**Comment by Raymond-001** [comment]
![image](https://user-images.githubusercontent.com/80483239/125160105-e5f5f900-e183-11eb-96a2-8647da674578.png)
other skins not showing

**Comment by Raymond-001** [comment]
my region tr

**Comment by Raymond-001** [comment]
https://cdn.discordapp.com/attachments/499582658981134356/863372887792418828/skin_data.json
https://cdn.discordapp.com/attachments/499582658981134356/863372890480181258/skincli.log
https://cdn.discordapp.com/attachments/499582658981134356/863372892376924160/config.json

**Comment by Raymond-001** [comment]
@colinhartigan
