### ISSUE TITLE
Setting Prime Karambit animation level. 

### ISSUE THREAD

**Issue by lhnpc** [colinhartigan/valorant-skin-cli#25]
On the latest version (**1.0.3**), when using the `set` command into the console to change the Prime Karambit level, a bug occurs where It does not seem able to identify the level 1 animation as a valid command, I even pasted the exact command prior to this version without success.

I'm not sure if it affects other melees or it's something specific to the Prime Karambit as it happens to be my only knife with 2 animations, but in version **1.0.2** it worked fine.

**Comment by colinhartigan** [comment]
i uploaded the wrong executable earlier, it has since been fixed (re-download v1.0.3)

**Comment by lhnpc** [comment]
Thanks a lot! Really love this program saving my Karambit Prime.

**Comment by colinhartigan** [comment]
no problem! funnily enough i didn't realize you could un-level skins until I finished all of the main randomizer functionality, but it's an awesome feature to have
