### ISSUE TITLE
[1.0.4] Exit command appears to not work correctly

### ISSUE THREAD

**Issue by PPatBoyd** [colinhartigan/valorant-skin-cli#26]
CLI version: 1.0.4
Winver: 20H2 (19042.1110)
ran by: click in explorer or run from cmd

repro steps:
1. open app
2. type exit, hit enter

expected:
app exits

actual:
app does not exit
![image](https://user-images.githubusercontent.com/41588892/126054181-ae0052d7-b6e0-4ebb-8ec0-72d9c7682581.png)

**Comment by colinhartigan** [comment]
should be fixed in [v1.0.5](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0.5)

**Comment by PPatBoyd** [comment]
confirmed!
