### ISSUE TITLE
File literally doesn't open. 

### ISSUE THREAD

**Issue by STUBBY4** [colinhartigan/valorant-skin-cli#27]
I've tried closing the game, getting out of the range, running in administrator, I even tried 1.0. I just can't get it to open.
It just says.
Traceback (most recent call)
  File "main.py", line 24, in <module>
  File "src\startup.py", line 38, in run
  File "src\utility\onboarding.py", line 19, in __init__
AttributeError: type object 'Config_Editor' has no attribute "set_region"
[1596] Failed to execute script main

https://user-images.githubusercontent.com/87613675/126075123-16b86022-1ad7-4124-af51-e17112f00693.mp4

**Comment by colinhartigan** [comment]
resolved in [v1.0.6](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0.6)

**Comment by STUBBY4** [comment]
thank you. Link worked just fine.
