### ISSUE TITLE
'Config_Editor had no attribute 'set_region' when trying to execute the compiled .exe

### ISSUE THREAD

**Issue by Arnaumes** [colinhartigan/valorant-skin-cli#28]
![image](https://user-images.githubusercontent.com/24882958/126083579-43e44232-b3f5-4ee6-b186-d35a977af5fb.png)
Thanks in advance for your help.

**Comment by colinhartigan** [comment]
resolved in [v1.0.6](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0.6)

**Comment by Arnaumes** [comment]
This issue is indeed fixed, although the program now doesn't detect my skins after selecting the "eu" region, should I make a new issue? Thanks for the help!
![image](https://user-images.githubusercontent.com/24882958/126126751-5304f0c6-3af1-47aa-ba53-a78a893611c8.png)

**Comment by colinhartigan** [comment]
try deleting the folder `%APPDATA%/valorant-rpc` and download [v1.0.7](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0.7)

**Comment by Arnaumes** [comment]
Fixed, thanks!
