### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by lamvor** [colinhartigan/valorant-skin-cli#29]
![2021-07-20 08_23_23-Windows Security](https://user-images.githubusercontent.com/87714113/126354296-cc0c0773-0d76-489e-8949-e54848c5e682.png)

**Comment by lamvor** [comment]
Is there an update on this issue? I really want to use the program, but there might be a compromise on the software.

**Comment by colinhartigan** [comment]
unfortunately, this is a side effect of using pyinstaller to build executables. if you'd like the full source code is available and you can build the executable yourself by running `build.bat`

**Comment by lamvor** [comment]
Oh ok, but the it’s safe to use and the code wasn’t hacked or anything? Sorry if it’s a dumb question just want to make sure

**Comment by colinhartigan** [comment]
it's safe. don't worry about it being a dumb question, it's great that you're aware of your pc's safety!

**Comment by lamvor** [comment]
Ok thank you! you are doing great work here keep it up!
