### ISSUE TITLE
.exe issue the list doesnt show my knife

### ISSUE THREAD

**Issue by ProbablyClive** [colinhartigan/valorant-skin-cli#30]
![Screenshot_33](https://user-images.githubusercontent.com/87743335/126425491-5fc4ca0b-902d-4988-9e88-15df1024118c.png)

**Comment by colinhartigan** [comment]
what region are you in? is usually happens when someone selected the wrong region

**Comment by ProbablyClive** [comment]
im in asia i clicked KR

**Comment by colinhartigan** [comment]
asia is in the AP region (asia/pacific)

**Comment by ProbablyClive** [comment]
ohh my bad how do i revert back

**Comment by colinhartigan** [comment]
run the `config` command and you can change your region there

**Comment by ProbablyClive** [comment]
thank u
