### ISSUE TITLE
does load any skin

### ISSUE THREAD

**Issue by ChocTitans** [colinhartigan/valorant-skin-cli#32]
![Screenshot_1](https://user-images.githubusercontent.com/25140207/126878127-311206de-39cd-4ebd-a463-323276c9a17d.png)

doesn't load any skins

**Comment by ChocTitans** [comment]
already have 
requests
InquirerPy
PyInstaller

**Comment by colinhartigan** [comment]
most likely selected wrong region, run `config` and adjust region accordingly

**Comment by colinhartigan** [comment]
please refer to this [wiki page](https://github.com/colinhartigan/valorant-skin-cli/wiki/setup#the-modify-command)

**Comment by ChocTitans** [comment]
followed every part of it, my region in config is eu and everything is correct

**Comment by ChocTitans** [comment]
nvm got it worked, ty
