### ISSUE TITLE
This is all that happens

### ISSUE THREAD

**Issue by sluggo87** [colinhartigan/valorant-skin-cli#34]
https://cdn.discordapp.com/attachments/860288780065701931/869133873529892894/unknown.png

**Comment by colinhartigan** [comment]
what region are you in?

**Comment by sluggo87** [comment]
Hey Colin!

I was able to find the appdata files and update my region and fix this,
thankfully your discord has some super helpful users and they got me going.

**Comment by colinhartigan** [comment]
awesome, glad you got it to work!
