### ISSUE TITLE
Invalid Region Error

### ISSUE THREAD

**Issue by ryanisho** [colinhartigan/valorant-skin-cli#35]
![unknown](https://user-images.githubusercontent.com/49701000/127035189-6f48217c-88d3-45be-a937-fb1dcc9287cc.png)

**Comment by colinhartigan** [comment]
what region are you in?

**Comment by ryanisho** [comment]
NA

**Comment by colinhartigan** [comment]
delete the folder `%APPDATA%/valorant-skin-cli` and run it again
