### ISSUE TITLE
Modified Levels for Melee level reset when relaunching CLI

### ISSUE THREAD

**Issue by RaySoyama** [colinhartigan/valorant-skin-cli#36]
I have the Prime 2.0 Karambit and I much prefer the level 1 base equip.
When I
- Modify/Melee/Prime 2.0/Level 2 disabled
- Randomize
This works properly

But when relaunching Valorant/CLI, the level 2 animation for the skin get's re-enabled

**Comment by RaySoyama** [comment]
Here is a video of the bug. (note, this link will die in ~30 days) 
[https://streamable.com/29h391](https://streamable.com/29h391)

**Comment by colinhartigan** [comment]
this might be a bug from the code that tries to prevent you from disabling every level, ill take a look into it

**Comment by colinhartigan** [comment]
resolved in [this commit](https://github.com/colinhartigan/valorant-skin-cli/commit/30d88269556e49002014a68c032069c01ec16cf8#diff-73f1ba0da54f0153c972571a58c12dbd1909cd02120ff6fc4387815f640d6ba6R227), will be live in the next release
