### ISSUE TITLE
Edge reports 1.1.0 release as containing a virus, preventing download

### ISSUE THREAD

**Issue by PPatBoyd** [colinhartigan/valorant-skin-cli#42]
No suggestion on the way forward for this one, not sure what's tripping it here.

![image](https://user-images.githubusercontent.com/41588892/128667302-5414c84e-7bc3-4654-ac75-88c196e062e4.png)

winver: 20H2 19042.1110
Edge ver: 92.0.902.67 (Official build) (64-bit)

**Comment by colinhartigan** [comment]
haven't changed anything major (no new required modules or anything), so i'm guessing its the usual false-positive trojan. hopefully it won't trip in the next release

**Comment by colinhartigan** [comment]
might be worth trying out [v1.2.1](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.2.1), it's getting a lower false-positive detection count on virustotal than other releases

**Comment by colinhartigan** [comment]
closed for inactivity
