### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Weintraubensaft** [colinhartigan/valorant-skin-cli#44]
![Screenshot 2021-08-11 032049](https://user-images.githubusercontent.com/88754172/128955692-4232fa30-5e43-4a01-9a89-a8e9ef9edf2d.png)
 I'm sorry if it's a stupid issue I just don't know what to do and im really stupid with stuff like that.

**Comment by isaacKenyon** [comment]
Use the release .exe instead of the .bat.
