### ISSUE TITLE
modify skin randomizer doesnt keep settings after exiting sidearm

### ISSUE THREAD

**Issue by SKATERGAMER127** [colinhartigan/valorant-skin-cli#46]
modify skin randomizer doesnt keep settings after exiting sidearm
![image](https://user-images.githubusercontent.com/87584849/130178180-71332774-0011-4222-a931-ce2bea217cca.png)
![image](https://user-images.githubusercontent.com/87584849/130178217-6e621a9b-14e6-41b4-90aa-ec229b866b07.png)

**Comment by colinhartigan** [comment]
fixed in [v1.2.1](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.2.1) :)
