### ISSUE TITLE
Modify settings don't carry over between updates

### ISSUE THREAD

**Issue by RaySoyama** [colinhartigan/valorant-skin-cli#47]
When ever updating the Valorant-ckin-cli.exe, all of my gun preferences gets reset.

**Comment by colinhartigan** [comment]
what version were you on and what version were you updating to?

preferences shouldn't reset

**Comment by RaySoyama** [comment]
I was updating to v1.2.0

When I say preferences, I refer to which gun skins/chromas/lvls I have enabled.

I have been simply overriding the exe with each update, is that the proper way to update them?

**Comment by colinhartigan** [comment]
very odd, i don't know of anyone else who's encountered this issue

you're updating it correctly, just use the new exe instead of the old one

**Comment by RaySoyama** [comment]
I'll try getting a video of it occurring later

**Comment by RaySoyama** [comment]
xd, can't repo. I'll close this issue.

**Comment by colinhartigan** [comment]
ig that's a good thing 😂
