### ISSUE TITLE
[Design] "randomize" command randomizes both skins and buddies, even though buddy_randomizer disabled in config

### ISSUE THREAD

**Issue by RaySoyama** [colinhartigan/valorant-skin-cli#48]
I'm not sure if this is intended behavior, since personally speaking, I'm only using the skin-cli for the skins, not the buddies. 

I would hope running "randomize" only randomizes skins, and then if you add a parameter such as "all", or "buddies", it will randomize those.

Having the default randomize behavior be only skins for 9 releases, only for it to change is jarring. 

Also whats does the "buddy_randomizer" bool do?

**Comment by colinhartigan** [comment]
great feedback, i'll change this for the next release (a lot of the discrepancy with UX will be alleviated once i make a gui version)

if buddy_randomizer is enabled it'll randomize your buddies after each match

**Comment by colinhartigan** [comment]
resolved in https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.2.3
