### ISSUE TITLE
Modify settings don't save.

### ISSUE THREAD

**Issue by tritonZZZ** [colinhartigan/valorant-skin-cli#49]
After enabling all weapons in the modify tab, the second you exit it all the skins go back to disabled.
Impossible to add skins to pool when all guns become disabled the second you leave the modify tab.

Thank you so much for the program btw, its amazing~

**Comment by colinhartigan** [comment]
fixed in [v1.2.1](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.2.1) :)
