### ISSUE TITLE
Skins not being detected.

### ISSUE THREAD

**Issue by ar1a** [colinhartigan/valorant-skin-cli#5]
Hi, I'm on OCE server and trying to run the randomiser. ![](https://i.imgur.com/ns7UwzA.png) yet I have quite a lot of skins. Willing to help debug in any way I can :)

**Comment by skittles9823** [comment]
Looks like it only works for NA users by default, if you wan't a quick fix, open main.py and change line 21 to this:
`client = Client(region="ap")`

**Comment by colinhartigan** [comment]
adding a command to set region/other config stuff soon

**Comment by colinhartigan** [comment]
addressed in [new commit](https://github.com/colinhartigan/valorant-skin-cli/commit/973dee78becbfbda1c6f3cfd9f7e929f823ae8ec#diff-77765503b3f273fa49a93e1c5bfa59786213a26f2143d7a6ad75fbd2c38d5cd2)
