### ISSUE TITLE
When using "enable all skins/chromas" in the modify setting, the changes do not save

### ISSUE THREAD

**Issue by RaySoyama** [colinhartigan/valorant-skin-cli#52]
I added a video of the bug occurring.

The settings to "Enable all skins/chromas" doesn't save properly

https://user-images.githubusercontent.com/42445829/131595601-f74cd92a-7f7c-40de-81be-5d3e642a4111.mov

**Comment by colinhartigan** [comment]
i've fixed this in the latest beta, will be released with v1.3.0

**Comment by colinhartigan** [comment]
fixed in [v1.2.1](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.2.1) :)
