### ISSUE TITLE
[Feature Request] Skin / Buddy combos

### ISSUE THREAD

**Issue by Lorphex** [colinhartigan/valorant-skin-cli#54]
I would love a way to tell the randomizer to change to a specific buddy / set of buddies when a skin is changed.
ie if I get the purple Ruination Phantom, I want to be able to tell the randomizer to pick from a set of buddies that match that skin. Dimensional fragment, Reaver, or Soul Capsule.

Could look something like this in the `modify` menu
[EXC] Ruination Phantom (4 levels, 2 chromas, 3 buddies)

**Comment by colinhartigan** [comment]
i've thought about potentially doing this and i'm glad people want to see it implemented!

**Comment by colinhartigan** [comment]
im planning to do this in the gui version of skincli, [VSM](https://github.com/colinhartigan/valorant-skin-manager), but it's way down the line

feel free to open an issue on that repo so i dont forget
