### ISSUE TITLE
Bug: Exception in Thread-1

### ISSUE THREAD

**Issue by RaySoyama** [colinhartigan/valorant-skin-cli#57]
Running into this assert. 
Attached a screenshot, and the log below
![image](https://user-images.githubusercontent.com/42445829/132971578-baeefc44-8d28-46d8-be85-a4d315ac8da0.png)
[skincli.log](https://github.com/colinhartigan/valorant-skin-cli/files/7148968/skincli.log)

**Comment by colinhartigan** [comment]
is this still happening?

**Comment by RaySoyama** [comment]
Yes, but it also doesn't crash the cli, and it still seems to run normally.
